
Задача 1 - Сложение и изменение формы массивов:

● Создайте два одномерных массива из случайных целых чисел от 1 до 10.

● Выполните поэлементное сложение этих двух массивов.

● Измените форму полученного массива на матрицу 2x5.

● Посчитайте среднее значение

In [21]:
import numpy as np

array1 = np.random.randint(1, 11, size=10)
print(array1)
array2 = np.random.randint(1, 11, size=10)
print(array2)

sum_array = array1+array2

print("поэлементное сложение этих двух массивов:\n", sum_array)

sum_array = sum_array.reshape((2,5))
print("изменение формы массива на матрицу 2х5:\n", sum_array)
sum_array_mean = sum_array.mean()
sum_array_mean

[ 2  5  8 10  8  5  6  3  8  9]
[ 8  7  6  3 10  6  1  1  1  9]
поэлементное сложение этих двух массивов:
 [10 12 14 13 18 11  7  4  9 18]
изменение формы массива на матрицу 2х5:
 [[10 12 14 13 18]
 [11  7  4  9 18]]


11.6

Задача 2 - Работа со срезами и формами:

● Создайте массив размером 3x3 и выведите его первую строку и первый столбец.

● Измените форму массива с помощью функции reshape и выведите его новую форму.

● Используйте функцию flatten, чтобы преобразовать массив в одномерный.

In [28]:
array3d = np.random.randint(1, 100, size=(3,3,3))
print("массив размером 3x3:\n", array3d)

array3d = array3d.reshape(3,9)
print("массив размером 3x9:\n", array3d)

array3d= array3d.flatten()
print("одномерный массив:\n", array3d)

массив размером 3x3:
 [[[76 37 72]
  [83 87 17]
  [13 87 13]]

 [[24 11 42]
  [31 12 81]
  [76 75 20]]

 [[22 22 81]
  [76  9 60]
  [15 69 40]]]
массив размером 3x9:
 [[76 37 72 83 87 17 13 87 13]
 [24 11 42 31 12 81 76 75 20]
 [22 22 81 76  9 60 15 69 40]]


array([76, 37, 72, 83, 87, 17, 13, 87, 13, 24, 11, 42, 31, 12, 81, 76, 75,
       20, 22, 22, 81, 76,  9, 60, 15, 69, 40])

Задача 3 - Генерация массива и объединение столбцов:

● Создайте двумерный массив размером 4x3 с случайными целыми числами от 1 до 10.

● Объедините столбцы этого массива в один столбец с использованием vstack.

In [33]:

arr = np.random.randint(1, 11, size=(4, 3))
print("Двумерный массив размером 4x3:\n", arr)

# Извлекаем каждый столбец как отдельный массив
# и объединяем эти столбцы в один столбец
combined_column = np.vstack([arr[:, i] for i in range(arr.shape[1])]).reshape(-1, 1)

print("\nСтолбцы, объединенные в один столбец:\n", combined_column)


Двумерный массив размером 4x3:
 [[ 6  1  2]
 [ 8 10  4]
 [ 4  5  5]
 [ 8  4 10]]

Столбцы, объединенные в один столбец:
 [[ 6]
 [ 8]
 [ 4]
 [ 8]
 [ 1]
 [10]
 [ 5]
 [ 4]
 [ 2]
 [ 4]
 [ 5]
 [10]]


Задача 4 - Генерация массива и индексирование:

● Создайте массив из 9 случайных чисел от 1 до 30.

● Найдите индекс максимального значения в массиве и выведите это значение.

In [38]:
array = np.random.randint(1, 31, size=9)
print("наш массив:", array)

# Инициализируем переменные для хранения максимального значения и его индекса
max_value = array[0]
max_index = 0

# Итерируем по массиву, начиная со второго элемента (индекс 1), так как первый уже учтен
for i in range(1, len(array)):
    if array[i] > max_value:
        max_value = array[i]
        max_index = i

print("Максимальное значение:", max_value)
print("Индекс максимального значения:", max_index)

наш массив: [14  3  9 13 21  8 22  2 27]
Максимальное значение: 27
Индекс максимального значения: 8


Задача 5 - Операции над массивами:

● Создайте два массива, каждый размером 2x2, состоящих из случайных целых чисел от 1 до 5.

● Транспонируйте один из массивов.

● Сложите транспонированный массив с другим массивом.

In [44]:
arr1 = np.random.randint(1,6, size=(2,2))
arr2 = np.random.randint(1,6, size=(2,2))
print("array1:\n", arr1)
print("array2:\n", arr2)
transpose = np.transpose(arr1)
print("transposed array:\n", transpose)
arr = np.concatenate((transpose,arr2), axis = 0)
print("concatenated array:\n", arr)


array1:
 [[2 5]
 [2 1]]
array2:
 [[1 5]
 [5 1]]
transposed array:
 [[2 2]
 [5 1]]
concatenated array:
 [[2 2]
 [5 1]
 [1 5]
 [5 1]]
